// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JavaScriptRegions
{
    static class Vsix
    {
        public const string Id = "74208c70-24ae-4899-ac91-658f11f0e65b";
        public const string Name = "JavaScript Regions";
        public const string Description = @"Adds support for region comments in JavaScript and TypeScript files";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "javascript, typescript, regions, comment";
    }
}
